version: '3'
services:
  redis:
    image: redis
    ports: 
      - '6379:6379'
  helm-minimal-app:
    build: .
    depends_on:
      - 'redis'
    env_file: '.env'
    tty: true
    ports:
      - '8080:8080'