apiVersion: apps/v1 
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  labels:
    name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.name }}
        app: {{ .Values.name }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: {{ .Values.name }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: REDIS_HOST
          valueFrom:
              configMapKeyRef:
                name: helm-minimal-configmap
                key: redis_host
        - name: REDIS_PORT
          valueFrom:
              configMapKeyRef:
                name: helm-minimal-configmap
                key: redis_port
        - name: APP_HOST
          valueFrom:
              configMapKeyRef:
                name: helm-minimal-configmap
                key: app_host
        - name: APP_PORT
          valueFrom:
              configMapKeyRef:
                name: helm-minimal-configmap
                key: app_port
        - name: FLASK_DEBUG
          valueFrom:
              configMapKeyRef:
                name: helm-minimal-configmap
                key: flask_debug
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: helm-minimal-secret
              key: redisPassword
