kind: Service
apiVersion: v1
metadata:
  name:  {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  type:  NodePort
  ports:
  - name:  http
    port:  {{ .Values.service.port }}
    targetPort:  {{ .Values.service.port }}


